import React from 'react';
import ShapChart from './ShapChart';


const timelineEvents = [
  {
    id: 'evt-001',
    time: '11-Jul-2026 12:08',
    event: 'New alert generated by Temporal GNN engine',
    type: 'alert',
    officer: 'System',
  },
  {
    id: 'evt-002',
    time: '11-Jul-2026 11:45',
    event: 'Transaction HDFC-4521 → KOTAK-8812 flagged — ₹1,99,000 (sub-threshold)',
    type: 'transaction',
    officer: 'System',
  },
  {
    id: 'evt-003',
    time: '11-Jul-2026 11:12',
    event: 'Pattern match: 47th deposit below ₹2L threshold confirmed — Smurfing typology',
    type: 'pattern',
    officer: 'GNN Engine',
  },
  {
    id: 'evt-004',
    time: '10-Jul-2026 14:30',
    event: 'Case CASE-0847 opened and assigned to Priya Mehta',
    type: 'case',
    officer: 'P. Mehta',
  },
  {
    id: 'evt-005',
    time: '10-Jul-2026 09:45',
    event: 'Initial triage completed — escalated from medium to critical risk',
    type: 'triage',
    officer: 'P. Mehta',
  },
  {
    id: 'evt-006',
    time: '10-Jul-2026 09:12',
    event: 'First structuring transaction detected — HDFC-4521 received ₹1,98,500',
    type: 'transaction',
    officer: 'System',
  },
  {
    id: 'evt-007',
    time: '05-Jul-2026 15:22',
    event: 'KYC review triggered — director network shows 23 linked shell companies',
    type: 'kyc',
    officer: 'A. Singh',
  },
];

const typeColors: Record<string, string> = {
  alert: 'text-risk-critical',
  transaction: 'text-risk-medium',
  pattern: 'text-risk-high',
  case: 'text-blue-400',
  triage: 'text-purple-400',
  kyc: 'text-muted-foreground',
};

const entityProfile = [
  { id: 'ep-type', label: 'Entity Type', value: 'Private Limited Company' },
  { id: 'ep-reg', label: 'Registration No.', value: 'U74999MH2019PTC324781', mono: true },
  { id: 'ep-directors', label: 'Directors', value: 'Suresh Ananya, Kavita Malhotra' },
  { id: 'ep-linked', label: 'Linked Companies', value: '23 (via director network)', alert: true },
  { id: 'ep-country', label: 'Registered Country', value: 'India (High-Risk Zone)' },
  { id: 'ep-kyc', label: 'KYC Status', value: 'Enhanced Due Diligence Required', alert: true },
  { id: 'ep-txn', label: 'Total Transactions', value: '847 in last 90 days', mono: true },
  { id: 'ep-amount', label: 'Total Amount', value: '₹1,47,32,000', mono: true },
];

export default function CaseOverviewTab() {
  return (
    <div className="grid grid-cols-1 xl:grid-cols-3 2xl:grid-cols-3 gap-4">
      {/* SHAP Analysis */}
      <div className="xl:col-span-2 card-elevated p-5">
        <div className="mb-4">
          <h3 className="text-sm font-semibold text-foreground">
            SHAP Feature Importance
          </h3>
          <p className="text-xs text-muted-foreground mt-0.5">
            Why this account scored 92/100 — GNNExplainer analysis
          </p>
        </div>
        <ShapChart />
        <div className="mt-4 p-3 bg-muted/40 rounded-lg border border-border">
          <p className="text-[10px] text-muted-foreground leading-relaxed">
            <span className="text-foreground font-semibold">Primary driver:</span> 47 deposits just
            below the ₹2,00,000 reporting threshold constitutes classic structuring (smurfing).
            Combined with connections to 3 confirmed shell companies and full pass-through
            behavior, this account presents a critical-risk profile consistent with FATF
            Typology 14 — Layering via structuring.
          </p>
        </div>
      </div>

      {/* Right column — Entity + Timeline */}
      <div className="flex flex-col gap-4">
        {/* Entity Profile */}
        <div className="card-elevated p-5">
          <h3 className="text-sm font-semibold text-foreground mb-3">Entity Profile</h3>
          <div className="space-y-2.5">
            {entityProfile.map((ep) => (
              <div key={ep.id} className="flex items-start justify-between gap-3">
                <p className="text-[10px] text-muted-foreground shrink-0 w-28">{ep.label}</p>
                <p
                  className={`text-[11px] text-right leading-tight ${
                    ep.alert
                      ? 'text-risk-critical font-semibold'
                      : ep.mono
                      ? 'font-mono text-foreground'
                      : 'text-foreground'
                  }`}
                >
                  {ep.value}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Case Timeline */}
        <div className="card-elevated p-5">
          <h3 className="text-sm font-semibold text-foreground mb-4">Investigation Timeline</h3>
          <div className="relative space-y-3">
            <div className="absolute left-2 top-2 bottom-2 w-px bg-border" />
            {timelineEvents.map((evt) => (
              <div key={evt.id} className="flex items-start gap-3 pl-6 relative">
                <div className="absolute left-0 top-1.5 w-4 h-4 rounded-full bg-card border border-border flex items-center justify-center">
                  <div className={`w-1.5 h-1.5 rounded-full ${typeColors[evt.type]}`} />
                </div>
                <div className="min-w-0 flex-1">
                  <p className="text-[10px] font-mono text-muted-foreground">{evt.time}</p>
                  <p className="text-xs text-foreground mt-0.5 leading-relaxed">{evt.event}</p>
                  <p className="text-[9px] text-muted-foreground mt-0.5">— {evt.officer}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}